version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
    env_file: .env  # Specify the path to your .env file
    volumes:
      - .:/app
  db:
    image: postgres:13.2
    container_name: postgres
    restart: always
    env_file: .env  # Specify the path to your .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
